# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: JFrogMaven@1
  inputs:
    mavenPomFile: 'maven-examples/maven-example/pom.xml'
    goals: 'clean install'
    artifactoryResolverService: 'JFrog'
    targetResolveReleaseRepo: 'vigneshs-libs-release'
    targetResolveSnapshotRepo: 'vigneshs-libs-snapshot'
    artifactoryDeployService: 'JFrog'
    targetDeployReleaseRepo: 'vigneshs-libs-release'
    targetDeploySnapshotRepo: 'vigneshs-libs-snapshot'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    javaHomeOption: 'JDKVersion'
- task: JFrogPublishBuildInfo@1
  inputs:
    artifactoryConnection: 'JFrog'
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'

