# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

parameters:
- name: artifactoryServiceConnection
  type: string
  default: vigneshs
- name: artifactoryPlatformOIDCServiceConnection
  type: string
  default: vigneshs

stages:
- stage: __default
  jobs:
  - job: Job
    steps:
    - script: echo "Hello, World!"
      displayName: 'Run a one-line script'

    - script: |
        echo "Add other tasks to build, test, and deploy your project."
        echo "See https://aka.ms/yaml"
      displayName: 'Run a multi-line script'
    
    # This task is removed as it relies on the jfrog_cli_temp_dir variable
    # - task: PowerShell@2
    #   displayName: Create JFROG_CLI_TEMP_DIR for JFrog CLI
    #   inputs:
    #     targetType: inline
    #     script: |
    #       if (!(Test-Path $(jfrog_cli_temp_dir))) {
    #         if($PSVersionTable.PSVersion.Major -eq '7') {
    #           mkdir -p $(jfrog_cli_temp_dir)
    #         } else {
    #           mkdir -Path $(jfrog_cli_temp_dir)
    #         }
    #       }
    #       Write-Host "$(jfrog_cli_temp_dir) now confirmed to exist"
    
    - task: JfrogCliV2@1
      name: jfStep
      inputs:
        jfrogPlatformConnection: 'vigneshs'
        command: 'jf rt ping'

    - task: PowerShell@2
      inputs:
        targetType: 'inline'
        script: |
          echo "OIDC Username: $($jfStep.oidc_user)"
          echo "OIDC Token: $env:oidc_token"
    
    - task: PowerShell@2
      displayName: Install curl dev tools and R
      inputs:
        targetType: inline
        script: sudo apt update && sudo apt-get -y install libcurl4-openssl-dev r-base-core
        pwsh: true
    
    - task: PowerShell@2
      displayName: Allow installation to hosts R library
      inputs:
        targetType: inline
        script: sudo chmod -R 777 /usr/local/lib/R
        pwsh: true
    
    - task: PowerShell@2
      displayName: Show OIDC details
      inputs:
        targetType: inline
        script: |
          echo "OIDC Username: $(jfStep.oidc_user)"
          echo "OIDC Token: $(oidc_token)"
        pwsh: true
    
    - task: PowerShell@2
      displayName: Create CRAN download script
      inputs:
        targetType: inline
        script: |
          $rscript = @'
            #!/usr/bin/env Rscript
            local({
                r <- list("cran-remote" = "http://localhost:8081/artifactory/cran-remote/")
                options(repos = r)
            })
            install.packages("ps", lib = "/usr/local/lib/R/site-library", repos = "http://localhost:8081/artifactory/cran-remote/")
            quit(status=0)
          '@
          Set-Content -Path './install_from_cran_remote.r' -Value $rscript
        pwsh: true
    
    - task: CmdLine@2
      displayName: Install ps from CRAN remote
      continueOnError: true
      inputs:
        script: |
          Rscript install_from_cran_remote.r
    
    - task: CmdLine@2
      displayName: Show R site-library
      inputs:
        script: |
          echo "/usr/local/lib/R/site-library"
          ls -al /usr/local/lib/R/site-library